### PR TITLE
Netcraft scraper container

### PR DESCRIPTION
**Pull request by SpyrosMArtel**
New container: Netcraft website scraper for passive fingerprinting.

### CODE REVIEW

**Comment by jherrlin** [comment]
Nice! 👍 Are your tests working locally @SpyrosMArtel ?

**Comment by SpyrosMArtel** [comment]
If you mean owtf.sh test, yes. Deployment is also working just fine and I get results too.

**Comment by SpyrosMArtel** [comment]
Btw, I found something today which I am not sure if it is going to help. Some people faced the same issue and they changed:
sudo apt-get install **-y** -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine=1.10.1-0~trusty

To:
sudo apt-get install **--force-yes** -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine=1.10.1-0~trusty

**Comment by jherrlin** [comment]
@SpyrosMArtel Yeah, i just run the tests locally and they are working here to! I guess what you found could be the reason that the tests fails for Travis! Would you like to do a PR on a fix?

**Comment by SpyrosMArtel** [comment]
Yes, np! What do I need to change? :)

**Comment by jherrlin** [comment]
@SpyrosMArtel The Travis settings are within .travis.yml in the project root. Line 15 is the commands :)

**Comment by jherrlin** [comment]
@SpyrosMArtel Apply the latest commits from master to this, if all tests working i will merge it! 👍

**Pull request merged**
